name: findGwangmyeong

on:
  push:
    branches: 
      - main 
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code.
      uses: actions/checkout@v3

    - name: Install Yarn
      run: npm install -g yarn

    - name: Check Node v
      run: node -v
      
    - name: Install dependencies     
      run: yarn install

    - name: Build                   
      run: yarn build
