name: findGwangmyeong

on:
  push:
    branches: 
      - main 

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest

    env:
      CI: false
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies     
      run: yarn install

    - name: Build                  
      run: yarn build
      env:
          NODE_ENV: production
          
    - uses: peaceiris/actions-gh-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
